name: e2e-tests
on: workflow_dispatch
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          node-version: '14'
        env:
          QA_USER_NAME: ${{secrets.QA_USER_NAME}}
          QA_PASSWORD: ${{secrets.QA_PASSWORD}}
      - run: npm install
      - run: npm run cy:run:qa
