name: e2e-tests-cy
on: workflow_dispatch
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v5
        env:
          QA_USER_NAME: ${{secrets.QA_USER_NAME}}
          QA_PASSWORD: ${{secrets.QA_PASSWORD}}
        with:
          command: npm run cy:run:qa
          env: environment=qa
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: /home/runner/work/cypressStudy/cypressStudy/cypress/reports/html/*
