name: e2e-tests
on: worfklow_dispatch
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v5
        env:
          QA_USER_NAME: ${{secrets.QA_USER_NAME}}
          QA_PASSWORD: ${{secrets.QA_PASSWORD}}
        with:
          start: npm run cy:run:qa
